dist: bionic
language: ruby
rvm: 2.7
before_script:
  - export MITIE_MODELS_VERSION=0.2
  - ./test/ci/install_models.sh
  - export MITIE_NER_PATH=MITIE-models/english/ner_model.dat
  - bundle exec rake vendor:linux
cache:
  directories:
    - $HOME/MITIE-models
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
