environment:
  matrix:
    - RUBY_VERSION: "26-x64"

cache:
  - vendor/bundle
  - "%USERPROFILE%/MITIE-models"

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - ridk enable
  - set HOME=%USERPROFILE%
  - set MITIE_MODELS_VERSION=0.2
  - sh ./test/ci/install_models.sh
  - set MITIE_NER_PATH=%HOME%/MITIE-models/%MITIE_MODELS_VERSION%/english/ner_model.dat
  - bundle exec rake vendor:windows

test_script:
  - bundle exec rake test
